/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/status` | `/status`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/appointments` | `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/revenue` | `/revenue`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schools` | `/schools`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/students` | `/students`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/school/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/student/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/status` | `/status`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/appointments` | `/appointments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/revenue` | `/revenue`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/schools` | `/schools`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/students` | `/students`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/school/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/student/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/otp${`?${string}` | `#${string}` | ''}` | `/otp${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/status${`?${string}` | `#${string}` | ''}` | `/status${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/appointments${`?${string}` | `#${string}` | ''}` | `/appointments${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/revenue${`?${string}` | `#${string}` | ''}` | `/revenue${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/schools${`?${string}` | `#${string}` | ''}` | `/schools${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/students${`?${string}` | `#${string}` | ''}` | `/students${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/status` | `/status`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/appointments` | `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/revenue` | `/revenue`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/schools` | `/schools`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/students` | `/students`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/school/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/student/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/school/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/student/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
